security.jwt.token.secret-key: my-secret-key

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/videojwtangular
    username: postgres
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  mvc:
    log-request-details: true

logging:
  level:
    org.springframework.web: debug
    org.hibernate.SQL: INFO
  file:
    name: D:/Aziz/codes/sergiolema/log/myapp.log
